addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.3")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.6.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "1.0.2")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.9")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.5")
addSbtPlugin("org.planet42"      % "laika-sbt"           % "0.18.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.6")